# "version" attribute is removed.

services:
  backend:
    build: ./backend
    container_name: corpus_backend
    env_file: .env
    volumes:
      - ./backend:/app
      - corpus_files:/app/corpus_files
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - elasticsearch
    networks:
      - corpus-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: corpus_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - corpus-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: corpus_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # --- THE TWO KEY CHANGES FOR THIS FIX ---
      - HOST=0.0.0.0
      - WDS_SOCKET_PORT=0 # Tells WebSocket server not to use a specific port, solving proxy issues
    networks:
      - corpus-net

  nginx:
    build: ./nginx
    container_name: corpus_nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    networks:
      - corpus-net

  certbot:
    image: certbot/certbot
    container_name: corpus_certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt

networks:
  corpus-net:
    driver: bridge

volumes:
  esdata:
  corpus_files:
  certbot_www:
  certbot_conf: