services:
  backend:
    build: ./backend
    container_name: corpus_backend
    env_file: .env
    volumes:
      - ./backend:/app
      - corpus_files:/app/corpus_files
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # We remove depends_on, as the application-level retry in session.py is more robust
    networks:
      - corpus-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: corpus_elasticsearch
    environment:
      - node.name=es01 # Give the node a predictable name
      - discovery.type=single-node
      - "cluster.initial_master_nodes=es01" # Use the predictable name to bootstrap the cluster
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - corpus-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: corpus_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - WDS_SOCKET_PATH=/ws
    networks:
      - corpus-net

  nginx:
    build: ./nginx
    container_name: corpus_nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend # Nginx should still wait for the backend service to exist
      - frontend
    networks:
      - corpus-net

  certbot:
    image: certbot/certbot
    container_name: corpus_certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt

networks:
  corpus-net:
    driver: bridge

volumes:
  esdata:
    driver: local
  corpus_files:
    driver: local
  certbot_www:
    driver: local
  certbot_conf:
    driver: local