services:
  backend:
    build: ./backend
    container_name: corpus_backend
    env_file: .env
    volumes:
      - ./backend:/app
      - corpus_files:/app/corpus_files
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # --- THE ARCHITECTURAL CHANGE ---
    # This service joins the network namespace of the 'elasticsearch' service.
    # It will NOT get its own IP on the corpus-net bridge.
    network_mode: "service:elasticsearch"
    depends_on:
      - elasticsearch # Still needs ES to exist before joining.

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: corpus_elasticsearch
    environment:
      # We can revert to the simplest, most correct configuration for single-node now.
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      # Expose both ES and the Backend's port on this container
      - "9200:9200"
    networks:
      # This service is the gateway for other services like Nginx to find it
      - corpus-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: corpus_frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - WDS_SOCKET_PATH=/ws
    networks:
      - corpus-net

  nginx:
    build: ./nginx
    container_name: corpus_nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # depends_on still works, as it checks for container existence
      - backend 
      - frontend
    networks:
      - corpus-net

networks:
  corpus-net:
    driver: bridge

volumes:
  esdata:
  corpus_files:
  certbot_www:
  certbot_conf: